[package]
name = "script-macro"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
wallet = { path = "../wallet" }
hex="0.4.3"
quote = "1.0"
