[package]
name = "btc-wallet"
version = "0.1.0"
authors = ["Leonardo Felipe Nerone <leonardofelipenerone@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
